name: tweet-once-a-day
on:
  schedule:
  - cron: '33 0 * * *'

env:
  CONSUMER_KEY: ${{ secrets.CONSUMER_KEY }}
  CONSUMER_SECRET: ${{ secrets.CONSUMER_SECRET }}
  TOKEN: ${{ secrets.TOKEN }}
  TOKEN_SECRET: ${{ secrets.TOKEN_SECRET }}
  AIRTABLE_BASE: ${{ secrets.AIRTABLE_BASE }}
  AIRTABLE_KEY: ${{ secrets.AIRTABLE_KEY }}

jobs:
  job1:
    name: run-scheduler 
    runs-on: ubuntu-latest
    steps: 
      - name: Git checkout
        uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with: 
          python-version: '3.8'
      - name: Install packages
        run: pip install -r requirements.txt
      - name: Run python script
        shell: python
        run: |
          from twitter import *
          from airtable import airtable
          t = Twitter(auth=OAuth(${{ env.TOKEN }}, ${{ env.TOKEN_SECRET }}, ${{ env.CONSUMER_KEY }}, ${{ env.CONSUMER_SECRET}}))
          at = airtable.Airtable(${{ env.AIRTABLE_BASE }}, ${{ env.AIRTABLE_KEY }})
          result = at.get(table_name='Tweets',max_records=1,view="Today")
          tweet = result['records'][0]['fields']['Tweet']
          t.statuses.update(status=tweet)
